name: "Build Docker file"
on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
    Building:
        name: Buiding docker file 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Dockerfile to build
              run: | 
                 data=()
                 for i in $(git diff --name-only ${{github.event.before}} ${{github.event.after}} | \
                   grep dockerfile | cut -d "/" -f 2 | sort -u )
                 do
                   echo "$i"
                   data+=($i)
                 done
                 echo "Files that needs to be build ${data[@]}"
                      
            - name: Installing Docker  
              run: |
                  cat /etc/os-release
                  sudo apt update
                  sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                  sudo apt update
                  sudo apt install -y docker-ce
                  docker version
            - name: Building image
              run: |
                for i in ${data[@]}
                do
                docker build -f ${{github.workspace }}/dockerfile/$i -t $i .
                done
                docker image list   
        
                
