name: Build_layer
on: 
  push:
    path:
      - "api/*/requirements.txt"
      - "!api/Layers/*"
permissions:
  id-token: write
  contents: read
jobs:
  Checkout-code:
    name: Checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload-artifact
        uses: actions/upload-artifact@v4 
        with:
          name: repo 
          path: .
  Build_layer:
    name: Build_layer
    runs-on: ubuntu-latest
    needs: Checkout-code
    steps:
      - name: Download-artifact
        uses: actions/download-artifact@v4
        with:
          name: repo
          path: .
      - name: Setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip 
      - name: Installing-dependencies
        run: |
          cd ./api/sayingthanks
          pip install -r requirements.txt --target ../Layers/python/lib/python3.12/site-packages
          cd ../Layers
          zip -r layer.zip ./python/lib/python3.12/site-packages
      - name: Upload-layer-artifact
        uses: actions/upload-artifact@v4
        with:
          name: layer-artifact
          path: ${{ github.workspace }}/api/Layers/layer.zip
  Upload-layer-to-s3:
    name: Upload-layer
    runs-on: ubuntu-latest
    needs: Build_layer
    steps:
      - name: Assume-IAM
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: "arn:aws:iam::975050222078:role/oidc-role-for-github"
          role-session-name: aws-main-role-for-layer
      - name : Download-artifact
        uses: actions/download-artifact@v4
        with: 
          name: layer-artifact
          path: . 
      - name: upload-to-s3
        run: |
          aws s3 cp ${{ github.workspace }}/layer.zip s3://python-package-api/api/lambda_layer.zip --region ap-south-1             
               



     
