name: "Build Docker file"
on: workflow_dispatch

jobs:
    Checkout:
        name: Checkout and Creating artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                path: .


    Building:
        name: Buiding docker file 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
               name: code
               fetch-depth: 0
            - name: Dockerfile to build 
              run: |
                echo "${{ github.event.before }}" 
            # - name: Installing Docker  
            #   run: |
            #     cat /etc/os-release
            #     sudo apt update
            #     sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
            #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            #     sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            #     sudo apt update
            #     sudo apt install -y docker-ce
            #     docker version
            # - name: Building image
            #   run: |
            #     docker build -f ${{github.workspace }}/dockerfile/baseimage -t basefile .
            #     docker image list   
         
                
