name: githubaction env testing 
on:
    push:
        branches:
            - "main"


jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        environment: testing
        steps:
            - name: firststep
              run: |
               echo " hello testing"
               echo "${{secrets.MYSECRET}}"
               echo "${{vars.MYVARIABLE}}"
