name: Build_lambda
on: push
permissions:
    id-token: write
    contents: read
jobs:
    Build_lambda:
          name: Build_lambda
          runs-on: ubuntu-latest
          steps:
            - name: Checkout_code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Upload_artifact
              uses: actions/upload-artifact@v4
              with:
                name: repo
                path: .
            - name: Install_python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: pip
            - name: installing_dependencies
              run: |
                cd api/sayingthanks
                ls
                pip install -r requirements.txt --target ./package
                cd package
                echo "inside package"
                ls
                zip -r ../my_deployment_package.zip .
                ls
                cd ..
                echo "comming out of package"
                ls
                zip my_deployment_package.zip lambda_function.py
                echo "after zipping"
                pwd
                ls
                aws s3 cp ${{ github.workspace }}api/sayingthanks/my_deployment_package.zip s3://python-package-api/api/sayingthanks/python_code.zip
               

                 



