name: Build_lambda
on: 
  push:
    paths:
      - "api/**"
      - "!api/Layers/**"
      - "!api/*/requirements.txt"
permissions:
    id-token: write
    contents: read
jobs:
    Build_lambda_and_upload:
          name: Build_lambda
          runs-on: ubuntu-latest
          steps:
            - name: Checkout_code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Upload_artifact
              uses: actions/upload-artifact@v4
              with:
                name: repo
                path: .
            - name: Install_python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: pip
            - name: installing_dependencies
              run: |
                cd api/sayingthanks
                pip install -r requirements.txt --target ./package
                zip -r lambda_layer.zip ./package
                zip lambda_layer.zip lambda_function.py
                ls
            - name: Assume_role
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ap-south-1
                role-to-assume: "arn:aws:iam::975050222078:role/oidc-role-for-github"
                role-session-name: aws-main-role  
            - name: Copying-package
              run: |  
                aws s3 cp ${{ github.workspace }}/api/sayingthanks/lambda_function.zip s3://python-package-api/api/sayingthanks/lambda_function.zip --region ap-south-1
            

                 



