name: Infratructure
run-name : ${{ github.actor }}
on : push 
permissions:
  id-token: write
  contents: read
jobs: 
  checkout-code:
    name: Check out code 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload_artifact
        uses: actions/upload-artifact@v4
        with:
            name: github-repo
            path: .
   
  Terraform-action:
    name: Terraform_action
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Download-artifact
        uses: actions/download-artifact@v4
        with:
          name: github-repo
          path: .
      - name: Assume_role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: "arn:aws:iam::975050222078:role/oidc-role-for-github"
          role-session-name: aws-main-role

      - name: Install_terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with: 
          terraform_verision: "1.1.7"
          terraform_wrapper: false
      - name: Terraform_FMT
        run : |
              echo "${{ github.workspace }}"
              ls
              echo "${{ github.workspace }}"
              cd terraform
              ls
              terraform fmt
      - name: Terraform_init
        run: |
            echo "${{ github.workspace }}"
            cd terraform
            terraform init --auto-approve
      - name: Terraform plan
        run: |
           ls
           cd terraform
           terraform plan 


                   
