name: "Testing some random actions"
on: workflow_dispatch


jobs:
    firstjob:
        name: first-job
        runs-on: ubuntu-latest
        strategy:
          matrix:
            os: [linux,mac,windows]
            version: [1,2,3,4]
        steps:
         - name: first-step
           run: | 
              echo "first job"
              echo "${{matrix.os}}"
         - name: second step
           run: |
             echo "second job ${{matrix.version}}"
    secondjob:
        name: second-job
        runs-on: ubuntu-latest
        steps:
            - name: second first step
              run: |
               echo "second first"
            - name: second second step
              run: |
               echo "second second"   
    third-job:
        name: third job 
        strategy:
          matrix:
            os: [mac,linux]
        runs-on: ubuntu-latest
        steps:
            - name: third first
              run: |
               echo "third first"
            - name: third second 
              run: |s
               echo "third second"   
    forth-job:
      name: forth job
      strategy:
        matrix:
          version: [0,1]
      needs: third-job
      runs-on: ubuntu-latest
      steps:
        - name: forth first
          run: |
            echo "forth first"
        - name: forth second
          run: |
            echo "forth second"                         