name: "Github outputs"
on:
  push:
    branches:
        - main

jobs:
   firstjob: 
    name: first job
    runs-on: ubuntu-latest
    outputs:
        mydata: ${{steps.first.outputs.firstoutput}}
    steps:
        - name: 'firststep'
          id: first
          run: |
            name="Abhishek"
            echo "firstoutput=$name" >> "$GITHUB_OUTPUT"
        - name: secondjob
          run: |
            outputdata=${{steps.first.outputs.firstoutput}}
            echo "data =>> ${outputdata}"
   secondjob:
     name: secondjob
     runs-on: ubuntu-latest
     needs: [firstjob]
     steps:
       - name: sec-first
         run: |
           outputdatafetch=${{needs.firstjob.outputs.mydata}}
           echo "data fetched in second job ${{needs.firstjob.outputs.mydata}}"



