name: Find Commit IDs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  find-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print commit IDs
        run: |
          echo "Current commit SHA: ${{ github.sha }}"
          echo "Previous commit SHA: ${{ github.event.before }}"
